// source: ibc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.penumbra.ibc.ICS20Withdrawal');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.penumbra.crypto.Address');
goog.require('proto.penumbra.crypto.Value');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.penumbra.ibc.ICS20Withdrawal = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.penumbra.ibc.ICS20Withdrawal, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.penumbra.ibc.ICS20Withdrawal.displayName = 'proto.penumbra.ibc.ICS20Withdrawal';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.penumbra.ibc.ICS20Withdrawal.prototype.toObject = function(opt_includeInstance) {
  return proto.penumbra.ibc.ICS20Withdrawal.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.penumbra.ibc.ICS20Withdrawal} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.ibc.ICS20Withdrawal.toObject = function(includeInstance, msg) {
  var f, obj = {
    destinationChainId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    value: (f = msg.getValue()) && proto.penumbra.crypto.Value.toObject(includeInstance, f),
    destinationChainAddress: jspb.Message.getFieldWithDefault(msg, 3, ""),
    returnAddress: (f = msg.getReturnAddress()) && proto.penumbra.crypto.Address.toObject(includeInstance, f),
    timeoutHeight: jspb.Message.getFieldWithDefault(msg, 6, 0),
    timeoutTime: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.penumbra.ibc.ICS20Withdrawal}
 */
proto.penumbra.ibc.ICS20Withdrawal.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.penumbra.ibc.ICS20Withdrawal;
  return proto.penumbra.ibc.ICS20Withdrawal.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.penumbra.ibc.ICS20Withdrawal} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.penumbra.ibc.ICS20Withdrawal}
 */
proto.penumbra.ibc.ICS20Withdrawal.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDestinationChainId(value);
      break;
    case 2:
      var value = new proto.penumbra.crypto.Value;
      reader.readMessage(value,proto.penumbra.crypto.Value.deserializeBinaryFromReader);
      msg.setValue(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDestinationChainAddress(value);
      break;
    case 5:
      var value = new proto.penumbra.crypto.Address;
      reader.readMessage(value,proto.penumbra.crypto.Address.deserializeBinaryFromReader);
      msg.setReturnAddress(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimeoutHeight(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimeoutTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.penumbra.ibc.ICS20Withdrawal.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.penumbra.ibc.ICS20Withdrawal.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.penumbra.ibc.ICS20Withdrawal} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.ibc.ICS20Withdrawal.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDestinationChainId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getValue();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.penumbra.crypto.Value.serializeBinaryToWriter
    );
  }
  f = message.getDestinationChainAddress();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getReturnAddress();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.penumbra.crypto.Address.serializeBinaryToWriter
    );
  }
  f = message.getTimeoutHeight();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getTimeoutTime();
  if (f !== 0) {
    writer.writeUint64(
      7,
      f
    );
  }
};


/**
 * optional string destination_chain_id = 1;
 * @return {string}
 */
proto.penumbra.ibc.ICS20Withdrawal.prototype.getDestinationChainId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.penumbra.ibc.ICS20Withdrawal} returns this
 */
proto.penumbra.ibc.ICS20Withdrawal.prototype.setDestinationChainId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional penumbra.crypto.Value value = 2;
 * @return {?proto.penumbra.crypto.Value}
 */
proto.penumbra.ibc.ICS20Withdrawal.prototype.getValue = function() {
  return /** @type{?proto.penumbra.crypto.Value} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.crypto.Value, 2));
};


/**
 * @param {?proto.penumbra.crypto.Value|undefined} value
 * @return {!proto.penumbra.ibc.ICS20Withdrawal} returns this
*/
proto.penumbra.ibc.ICS20Withdrawal.prototype.setValue = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.ibc.ICS20Withdrawal} returns this
 */
proto.penumbra.ibc.ICS20Withdrawal.prototype.clearValue = function() {
  return this.setValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.ibc.ICS20Withdrawal.prototype.hasValue = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string destination_chain_address = 3;
 * @return {string}
 */
proto.penumbra.ibc.ICS20Withdrawal.prototype.getDestinationChainAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.penumbra.ibc.ICS20Withdrawal} returns this
 */
proto.penumbra.ibc.ICS20Withdrawal.prototype.setDestinationChainAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional penumbra.crypto.Address return_address = 5;
 * @return {?proto.penumbra.crypto.Address}
 */
proto.penumbra.ibc.ICS20Withdrawal.prototype.getReturnAddress = function() {
  return /** @type{?proto.penumbra.crypto.Address} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.crypto.Address, 5));
};


/**
 * @param {?proto.penumbra.crypto.Address|undefined} value
 * @return {!proto.penumbra.ibc.ICS20Withdrawal} returns this
*/
proto.penumbra.ibc.ICS20Withdrawal.prototype.setReturnAddress = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.ibc.ICS20Withdrawal} returns this
 */
proto.penumbra.ibc.ICS20Withdrawal.prototype.clearReturnAddress = function() {
  return this.setReturnAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.ibc.ICS20Withdrawal.prototype.hasReturnAddress = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional uint64 timeout_height = 6;
 * @return {number}
 */
proto.penumbra.ibc.ICS20Withdrawal.prototype.getTimeoutHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.penumbra.ibc.ICS20Withdrawal} returns this
 */
proto.penumbra.ibc.ICS20Withdrawal.prototype.setTimeoutHeight = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint64 timeout_time = 7;
 * @return {number}
 */
proto.penumbra.ibc.ICS20Withdrawal.prototype.getTimeoutTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.penumbra.ibc.ICS20Withdrawal} returns this
 */
proto.penumbra.ibc.ICS20Withdrawal.prototype.setTimeoutTime = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


