// source: dex.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.penumbra.dex.SwapPlaintext');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.penumbra.crypto.Address');
goog.require('proto.penumbra.crypto.Fee');
goog.require('proto.penumbra.dex.TradingPair');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.penumbra.dex.SwapPlaintext = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.penumbra.dex.SwapPlaintext, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.penumbra.dex.SwapPlaintext.displayName = 'proto.penumbra.dex.SwapPlaintext';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.penumbra.dex.SwapPlaintext.prototype.toObject = function(opt_includeInstance) {
  return proto.penumbra.dex.SwapPlaintext.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.penumbra.dex.SwapPlaintext} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.dex.SwapPlaintext.toObject = function(includeInstance, msg) {
  var f, obj = {
    tradingPair: (f = msg.getTradingPair()) && proto.penumbra.dex.TradingPair.toObject(includeInstance, f),
    delta1: jspb.Message.getFieldWithDefault(msg, 2, 0),
    delta2: jspb.Message.getFieldWithDefault(msg, 3, 0),
    claimFee: (f = msg.getClaimFee()) && proto.penumbra.crypto.Fee.toObject(includeInstance, f),
    claimAddress: (f = msg.getClaimAddress()) && proto.penumbra.crypto.Address.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.penumbra.dex.SwapPlaintext}
 */
proto.penumbra.dex.SwapPlaintext.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.penumbra.dex.SwapPlaintext;
  return proto.penumbra.dex.SwapPlaintext.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.penumbra.dex.SwapPlaintext} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.penumbra.dex.SwapPlaintext}
 */
proto.penumbra.dex.SwapPlaintext.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.penumbra.dex.TradingPair;
      reader.readMessage(value,proto.penumbra.dex.TradingPair.deserializeBinaryFromReader);
      msg.setTradingPair(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDelta1(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDelta2(value);
      break;
    case 4:
      var value = new proto.penumbra.crypto.Fee;
      reader.readMessage(value,proto.penumbra.crypto.Fee.deserializeBinaryFromReader);
      msg.setClaimFee(value);
      break;
    case 5:
      var value = new proto.penumbra.crypto.Address;
      reader.readMessage(value,proto.penumbra.crypto.Address.deserializeBinaryFromReader);
      msg.setClaimAddress(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.penumbra.dex.SwapPlaintext.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.penumbra.dex.SwapPlaintext.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.penumbra.dex.SwapPlaintext} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.dex.SwapPlaintext.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTradingPair();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.penumbra.dex.TradingPair.serializeBinaryToWriter
    );
  }
  f = message.getDelta1();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getDelta2();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getClaimFee();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.penumbra.crypto.Fee.serializeBinaryToWriter
    );
  }
  f = message.getClaimAddress();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.penumbra.crypto.Address.serializeBinaryToWriter
    );
  }
};


/**
 * optional TradingPair trading_pair = 1;
 * @return {?proto.penumbra.dex.TradingPair}
 */
proto.penumbra.dex.SwapPlaintext.prototype.getTradingPair = function() {
  return /** @type{?proto.penumbra.dex.TradingPair} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.dex.TradingPair, 1));
};


/**
 * @param {?proto.penumbra.dex.TradingPair|undefined} value
 * @return {!proto.penumbra.dex.SwapPlaintext} returns this
*/
proto.penumbra.dex.SwapPlaintext.prototype.setTradingPair = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.dex.SwapPlaintext} returns this
 */
proto.penumbra.dex.SwapPlaintext.prototype.clearTradingPair = function() {
  return this.setTradingPair(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.dex.SwapPlaintext.prototype.hasTradingPair = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint64 delta_1 = 2;
 * @return {number}
 */
proto.penumbra.dex.SwapPlaintext.prototype.getDelta1 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.penumbra.dex.SwapPlaintext} returns this
 */
proto.penumbra.dex.SwapPlaintext.prototype.setDelta1 = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 delta_2 = 3;
 * @return {number}
 */
proto.penumbra.dex.SwapPlaintext.prototype.getDelta2 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.penumbra.dex.SwapPlaintext} returns this
 */
proto.penumbra.dex.SwapPlaintext.prototype.setDelta2 = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional penumbra.crypto.Fee claim_fee = 4;
 * @return {?proto.penumbra.crypto.Fee}
 */
proto.penumbra.dex.SwapPlaintext.prototype.getClaimFee = function() {
  return /** @type{?proto.penumbra.crypto.Fee} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.crypto.Fee, 4));
};


/**
 * @param {?proto.penumbra.crypto.Fee|undefined} value
 * @return {!proto.penumbra.dex.SwapPlaintext} returns this
*/
proto.penumbra.dex.SwapPlaintext.prototype.setClaimFee = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.dex.SwapPlaintext} returns this
 */
proto.penumbra.dex.SwapPlaintext.prototype.clearClaimFee = function() {
  return this.setClaimFee(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.dex.SwapPlaintext.prototype.hasClaimFee = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional penumbra.crypto.Address claim_address = 5;
 * @return {?proto.penumbra.crypto.Address}
 */
proto.penumbra.dex.SwapPlaintext.prototype.getClaimAddress = function() {
  return /** @type{?proto.penumbra.crypto.Address} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.crypto.Address, 5));
};


/**
 * @param {?proto.penumbra.crypto.Address|undefined} value
 * @return {!proto.penumbra.dex.SwapPlaintext} returns this
*/
proto.penumbra.dex.SwapPlaintext.prototype.setClaimAddress = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.dex.SwapPlaintext} returns this
 */
proto.penumbra.dex.SwapPlaintext.prototype.clearClaimAddress = function() {
  return this.setClaimAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.dex.SwapPlaintext.prototype.hasClaimAddress = function() {
  return jspb.Message.getField(this, 5) != null;
};


