// source: transaction.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.penumbra.transaction.TransactionBody');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.penumbra.crypto.Clue');
goog.require('proto.penumbra.crypto.Fee');
goog.require('proto.penumbra.transaction.Action');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.penumbra.transaction.TransactionBody = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.penumbra.transaction.TransactionBody.repeatedFields_, null);
};
goog.inherits(proto.penumbra.transaction.TransactionBody, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.penumbra.transaction.TransactionBody.displayName = 'proto.penumbra.transaction.TransactionBody';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.penumbra.transaction.TransactionBody.repeatedFields_ = [1,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.penumbra.transaction.TransactionBody.prototype.toObject = function(opt_includeInstance) {
  return proto.penumbra.transaction.TransactionBody.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.penumbra.transaction.TransactionBody} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.transaction.TransactionBody.toObject = function(includeInstance, msg) {
  var f, obj = {
    actionsList: jspb.Message.toObjectList(msg.getActionsList(),
    proto.penumbra.transaction.Action.toObject, includeInstance),
    expiryHeight: jspb.Message.getFieldWithDefault(msg, 2, 0),
    chainId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    fee: (f = msg.getFee()) && proto.penumbra.crypto.Fee.toObject(includeInstance, f),
    fmdCluesList: jspb.Message.toObjectList(msg.getFmdCluesList(),
    proto.penumbra.crypto.Clue.toObject, includeInstance),
    encryptedMemo: msg.getEncryptedMemo_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.penumbra.transaction.TransactionBody}
 */
proto.penumbra.transaction.TransactionBody.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.penumbra.transaction.TransactionBody;
  return proto.penumbra.transaction.TransactionBody.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.penumbra.transaction.TransactionBody} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.penumbra.transaction.TransactionBody}
 */
proto.penumbra.transaction.TransactionBody.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.penumbra.transaction.Action;
      reader.readMessage(value,proto.penumbra.transaction.Action.deserializeBinaryFromReader);
      msg.addActions(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setExpiryHeight(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setChainId(value);
      break;
    case 4:
      var value = new proto.penumbra.crypto.Fee;
      reader.readMessage(value,proto.penumbra.crypto.Fee.deserializeBinaryFromReader);
      msg.setFee(value);
      break;
    case 5:
      var value = new proto.penumbra.crypto.Clue;
      reader.readMessage(value,proto.penumbra.crypto.Clue.deserializeBinaryFromReader);
      msg.addFmdClues(value);
      break;
    case 6:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEncryptedMemo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.penumbra.transaction.TransactionBody.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.penumbra.transaction.TransactionBody.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.penumbra.transaction.TransactionBody} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.transaction.TransactionBody.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getActionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.penumbra.transaction.Action.serializeBinaryToWriter
    );
  }
  f = message.getExpiryHeight();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getChainId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFee();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.penumbra.crypto.Fee.serializeBinaryToWriter
    );
  }
  f = message.getFmdCluesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.penumbra.crypto.Clue.serializeBinaryToWriter
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeBytes(
      6,
      f
    );
  }
};


/**
 * repeated Action actions = 1;
 * @return {!Array<!proto.penumbra.transaction.Action>}
 */
proto.penumbra.transaction.TransactionBody.prototype.getActionsList = function() {
  return /** @type{!Array<!proto.penumbra.transaction.Action>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.penumbra.transaction.Action, 1));
};


/**
 * @param {!Array<!proto.penumbra.transaction.Action>} value
 * @return {!proto.penumbra.transaction.TransactionBody} returns this
*/
proto.penumbra.transaction.TransactionBody.prototype.setActionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.penumbra.transaction.Action=} opt_value
 * @param {number=} opt_index
 * @return {!proto.penumbra.transaction.Action}
 */
proto.penumbra.transaction.TransactionBody.prototype.addActions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.penumbra.transaction.Action, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.penumbra.transaction.TransactionBody} returns this
 */
proto.penumbra.transaction.TransactionBody.prototype.clearActionsList = function() {
  return this.setActionsList([]);
};


/**
 * optional uint64 expiry_height = 2;
 * @return {number}
 */
proto.penumbra.transaction.TransactionBody.prototype.getExpiryHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.penumbra.transaction.TransactionBody} returns this
 */
proto.penumbra.transaction.TransactionBody.prototype.setExpiryHeight = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string chain_id = 3;
 * @return {string}
 */
proto.penumbra.transaction.TransactionBody.prototype.getChainId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.penumbra.transaction.TransactionBody} returns this
 */
proto.penumbra.transaction.TransactionBody.prototype.setChainId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional penumbra.crypto.Fee fee = 4;
 * @return {?proto.penumbra.crypto.Fee}
 */
proto.penumbra.transaction.TransactionBody.prototype.getFee = function() {
  return /** @type{?proto.penumbra.crypto.Fee} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.crypto.Fee, 4));
};


/**
 * @param {?proto.penumbra.crypto.Fee|undefined} value
 * @return {!proto.penumbra.transaction.TransactionBody} returns this
*/
proto.penumbra.transaction.TransactionBody.prototype.setFee = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.transaction.TransactionBody} returns this
 */
proto.penumbra.transaction.TransactionBody.prototype.clearFee = function() {
  return this.setFee(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.transaction.TransactionBody.prototype.hasFee = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated penumbra.crypto.Clue fmd_clues = 5;
 * @return {!Array<!proto.penumbra.crypto.Clue>}
 */
proto.penumbra.transaction.TransactionBody.prototype.getFmdCluesList = function() {
  return /** @type{!Array<!proto.penumbra.crypto.Clue>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.penumbra.crypto.Clue, 5));
};


/**
 * @param {!Array<!proto.penumbra.crypto.Clue>} value
 * @return {!proto.penumbra.transaction.TransactionBody} returns this
*/
proto.penumbra.transaction.TransactionBody.prototype.setFmdCluesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.penumbra.crypto.Clue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.penumbra.crypto.Clue}
 */
proto.penumbra.transaction.TransactionBody.prototype.addFmdClues = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.penumbra.crypto.Clue, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.penumbra.transaction.TransactionBody} returns this
 */
proto.penumbra.transaction.TransactionBody.prototype.clearFmdCluesList = function() {
  return this.setFmdCluesList([]);
};


/**
 * optional bytes encrypted_memo = 6;
 * @return {!(string|Uint8Array)}
 */
proto.penumbra.transaction.TransactionBody.prototype.getEncryptedMemo = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * optional bytes encrypted_memo = 6;
 * This is a type-conversion wrapper around `getEncryptedMemo()`
 * @return {string}
 */
proto.penumbra.transaction.TransactionBody.prototype.getEncryptedMemo_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEncryptedMemo()));
};


/**
 * optional bytes encrypted_memo = 6;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEncryptedMemo()`
 * @return {!Uint8Array}
 */
proto.penumbra.transaction.TransactionBody.prototype.getEncryptedMemo_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEncryptedMemo()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.penumbra.transaction.TransactionBody} returns this
 */
proto.penumbra.transaction.TransactionBody.prototype.setEncryptedMemo = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.penumbra.transaction.TransactionBody} returns this
 */
proto.penumbra.transaction.TransactionBody.prototype.clearEncryptedMemo = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.transaction.TransactionBody.prototype.hasEncryptedMemo = function() {
  return jspb.Message.getField(this, 6) != null;
};


