// source: transaction.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.penumbra.transaction.Transaction');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.penumbra.crypto.MerkleRoot');
goog.require('proto.penumbra.transaction.TransactionBody');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.penumbra.transaction.Transaction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.penumbra.transaction.Transaction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.penumbra.transaction.Transaction.displayName = 'proto.penumbra.transaction.Transaction';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.penumbra.transaction.Transaction.prototype.toObject = function(opt_includeInstance) {
  return proto.penumbra.transaction.Transaction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.penumbra.transaction.Transaction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.transaction.Transaction.toObject = function(includeInstance, msg) {
  var f, obj = {
    body: (f = msg.getBody()) && proto.penumbra.transaction.TransactionBody.toObject(includeInstance, f),
    bindingSig: msg.getBindingSig_asB64(),
    anchor: (f = msg.getAnchor()) && proto.penumbra.crypto.MerkleRoot.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.penumbra.transaction.Transaction}
 */
proto.penumbra.transaction.Transaction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.penumbra.transaction.Transaction;
  return proto.penumbra.transaction.Transaction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.penumbra.transaction.Transaction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.penumbra.transaction.Transaction}
 */
proto.penumbra.transaction.Transaction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.penumbra.transaction.TransactionBody;
      reader.readMessage(value,proto.penumbra.transaction.TransactionBody.deserializeBinaryFromReader);
      msg.setBody(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBindingSig(value);
      break;
    case 3:
      var value = new proto.penumbra.crypto.MerkleRoot;
      reader.readMessage(value,proto.penumbra.crypto.MerkleRoot.deserializeBinaryFromReader);
      msg.setAnchor(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.penumbra.transaction.Transaction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.penumbra.transaction.Transaction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.penumbra.transaction.Transaction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.transaction.Transaction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBody();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.penumbra.transaction.TransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getBindingSig_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getAnchor();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.penumbra.crypto.MerkleRoot.serializeBinaryToWriter
    );
  }
};


/**
 * optional TransactionBody body = 1;
 * @return {?proto.penumbra.transaction.TransactionBody}
 */
proto.penumbra.transaction.Transaction.prototype.getBody = function() {
  return /** @type{?proto.penumbra.transaction.TransactionBody} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.transaction.TransactionBody, 1));
};


/**
 * @param {?proto.penumbra.transaction.TransactionBody|undefined} value
 * @return {!proto.penumbra.transaction.Transaction} returns this
*/
proto.penumbra.transaction.Transaction.prototype.setBody = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.transaction.Transaction} returns this
 */
proto.penumbra.transaction.Transaction.prototype.clearBody = function() {
  return this.setBody(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.transaction.Transaction.prototype.hasBody = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bytes binding_sig = 2;
 * @return {!(string|Uint8Array)}
 */
proto.penumbra.transaction.Transaction.prototype.getBindingSig = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes binding_sig = 2;
 * This is a type-conversion wrapper around `getBindingSig()`
 * @return {string}
 */
proto.penumbra.transaction.Transaction.prototype.getBindingSig_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBindingSig()));
};


/**
 * optional bytes binding_sig = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBindingSig()`
 * @return {!Uint8Array}
 */
proto.penumbra.transaction.Transaction.prototype.getBindingSig_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBindingSig()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.penumbra.transaction.Transaction} returns this
 */
proto.penumbra.transaction.Transaction.prototype.setBindingSig = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional penumbra.crypto.MerkleRoot anchor = 3;
 * @return {?proto.penumbra.crypto.MerkleRoot}
 */
proto.penumbra.transaction.Transaction.prototype.getAnchor = function() {
  return /** @type{?proto.penumbra.crypto.MerkleRoot} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.crypto.MerkleRoot, 3));
};


/**
 * @param {?proto.penumbra.crypto.MerkleRoot|undefined} value
 * @return {!proto.penumbra.transaction.Transaction} returns this
*/
proto.penumbra.transaction.Transaction.prototype.setAnchor = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.transaction.Transaction} returns this
 */
proto.penumbra.transaction.Transaction.prototype.clearAnchor = function() {
  return this.setAnchor(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.transaction.Transaction.prototype.hasAnchor = function() {
  return jspb.Message.getField(this, 3) != null;
};


