// source: stake.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.penumbra.stake.ValidatorInfo');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.penumbra.stake.RateData');
goog.require('proto.penumbra.stake.Validator');
goog.require('proto.penumbra.stake.ValidatorStatus');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.penumbra.stake.ValidatorInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.penumbra.stake.ValidatorInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.penumbra.stake.ValidatorInfo.displayName = 'proto.penumbra.stake.ValidatorInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.penumbra.stake.ValidatorInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.penumbra.stake.ValidatorInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.penumbra.stake.ValidatorInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.stake.ValidatorInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    validator: (f = msg.getValidator()) && proto.penumbra.stake.Validator.toObject(includeInstance, f),
    status: (f = msg.getStatus()) && proto.penumbra.stake.ValidatorStatus.toObject(includeInstance, f),
    rateData: (f = msg.getRateData()) && proto.penumbra.stake.RateData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.penumbra.stake.ValidatorInfo}
 */
proto.penumbra.stake.ValidatorInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.penumbra.stake.ValidatorInfo;
  return proto.penumbra.stake.ValidatorInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.penumbra.stake.ValidatorInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.penumbra.stake.ValidatorInfo}
 */
proto.penumbra.stake.ValidatorInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.penumbra.stake.Validator;
      reader.readMessage(value,proto.penumbra.stake.Validator.deserializeBinaryFromReader);
      msg.setValidator(value);
      break;
    case 2:
      var value = new proto.penumbra.stake.ValidatorStatus;
      reader.readMessage(value,proto.penumbra.stake.ValidatorStatus.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 3:
      var value = new proto.penumbra.stake.RateData;
      reader.readMessage(value,proto.penumbra.stake.RateData.deserializeBinaryFromReader);
      msg.setRateData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.penumbra.stake.ValidatorInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.penumbra.stake.ValidatorInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.penumbra.stake.ValidatorInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.stake.ValidatorInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValidator();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.penumbra.stake.Validator.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.penumbra.stake.ValidatorStatus.serializeBinaryToWriter
    );
  }
  f = message.getRateData();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.penumbra.stake.RateData.serializeBinaryToWriter
    );
  }
};


/**
 * optional Validator validator = 1;
 * @return {?proto.penumbra.stake.Validator}
 */
proto.penumbra.stake.ValidatorInfo.prototype.getValidator = function() {
  return /** @type{?proto.penumbra.stake.Validator} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.stake.Validator, 1));
};


/**
 * @param {?proto.penumbra.stake.Validator|undefined} value
 * @return {!proto.penumbra.stake.ValidatorInfo} returns this
*/
proto.penumbra.stake.ValidatorInfo.prototype.setValidator = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.stake.ValidatorInfo} returns this
 */
proto.penumbra.stake.ValidatorInfo.prototype.clearValidator = function() {
  return this.setValidator(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.stake.ValidatorInfo.prototype.hasValidator = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ValidatorStatus status = 2;
 * @return {?proto.penumbra.stake.ValidatorStatus}
 */
proto.penumbra.stake.ValidatorInfo.prototype.getStatus = function() {
  return /** @type{?proto.penumbra.stake.ValidatorStatus} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.stake.ValidatorStatus, 2));
};


/**
 * @param {?proto.penumbra.stake.ValidatorStatus|undefined} value
 * @return {!proto.penumbra.stake.ValidatorInfo} returns this
*/
proto.penumbra.stake.ValidatorInfo.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.stake.ValidatorInfo} returns this
 */
proto.penumbra.stake.ValidatorInfo.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.stake.ValidatorInfo.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional RateData rate_data = 3;
 * @return {?proto.penumbra.stake.RateData}
 */
proto.penumbra.stake.ValidatorInfo.prototype.getRateData = function() {
  return /** @type{?proto.penumbra.stake.RateData} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.stake.RateData, 3));
};


/**
 * @param {?proto.penumbra.stake.RateData|undefined} value
 * @return {!proto.penumbra.stake.ValidatorInfo} returns this
*/
proto.penumbra.stake.ValidatorInfo.prototype.setRateData = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.stake.ValidatorInfo} returns this
 */
proto.penumbra.stake.ValidatorInfo.prototype.clearRateData = function() {
  return this.setRateData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.stake.ValidatorInfo.prototype.hasRateData = function() {
  return jspb.Message.getField(this, 3) != null;
};


