// source: transaction.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.penumbra.transaction.WitnessData');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.penumbra.crypto.MerkleRoot');
goog.require('proto.penumbra.crypto.NoteCommitmentProof');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.penumbra.transaction.WitnessData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.penumbra.transaction.WitnessData.repeatedFields_, null);
};
goog.inherits(proto.penumbra.transaction.WitnessData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.penumbra.transaction.WitnessData.displayName = 'proto.penumbra.transaction.WitnessData';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.penumbra.transaction.WitnessData.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.penumbra.transaction.WitnessData.prototype.toObject = function(opt_includeInstance) {
  return proto.penumbra.transaction.WitnessData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.penumbra.transaction.WitnessData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.transaction.WitnessData.toObject = function(includeInstance, msg) {
  var f, obj = {
    anchor: (f = msg.getAnchor()) && proto.penumbra.crypto.MerkleRoot.toObject(includeInstance, f),
    noteCommitmentProofsList: jspb.Message.toObjectList(msg.getNoteCommitmentProofsList(),
    proto.penumbra.crypto.NoteCommitmentProof.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.penumbra.transaction.WitnessData}
 */
proto.penumbra.transaction.WitnessData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.penumbra.transaction.WitnessData;
  return proto.penumbra.transaction.WitnessData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.penumbra.transaction.WitnessData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.penumbra.transaction.WitnessData}
 */
proto.penumbra.transaction.WitnessData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.penumbra.crypto.MerkleRoot;
      reader.readMessage(value,proto.penumbra.crypto.MerkleRoot.deserializeBinaryFromReader);
      msg.setAnchor(value);
      break;
    case 2:
      var value = new proto.penumbra.crypto.NoteCommitmentProof;
      reader.readMessage(value,proto.penumbra.crypto.NoteCommitmentProof.deserializeBinaryFromReader);
      msg.addNoteCommitmentProofs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.penumbra.transaction.WitnessData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.penumbra.transaction.WitnessData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.penumbra.transaction.WitnessData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.transaction.WitnessData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAnchor();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.penumbra.crypto.MerkleRoot.serializeBinaryToWriter
    );
  }
  f = message.getNoteCommitmentProofsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.penumbra.crypto.NoteCommitmentProof.serializeBinaryToWriter
    );
  }
};


/**
 * optional penumbra.crypto.MerkleRoot anchor = 1;
 * @return {?proto.penumbra.crypto.MerkleRoot}
 */
proto.penumbra.transaction.WitnessData.prototype.getAnchor = function() {
  return /** @type{?proto.penumbra.crypto.MerkleRoot} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.crypto.MerkleRoot, 1));
};


/**
 * @param {?proto.penumbra.crypto.MerkleRoot|undefined} value
 * @return {!proto.penumbra.transaction.WitnessData} returns this
*/
proto.penumbra.transaction.WitnessData.prototype.setAnchor = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.transaction.WitnessData} returns this
 */
proto.penumbra.transaction.WitnessData.prototype.clearAnchor = function() {
  return this.setAnchor(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.transaction.WitnessData.prototype.hasAnchor = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated penumbra.crypto.NoteCommitmentProof note_commitment_proofs = 2;
 * @return {!Array<!proto.penumbra.crypto.NoteCommitmentProof>}
 */
proto.penumbra.transaction.WitnessData.prototype.getNoteCommitmentProofsList = function() {
  return /** @type{!Array<!proto.penumbra.crypto.NoteCommitmentProof>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.penumbra.crypto.NoteCommitmentProof, 2));
};


/**
 * @param {!Array<!proto.penumbra.crypto.NoteCommitmentProof>} value
 * @return {!proto.penumbra.transaction.WitnessData} returns this
*/
proto.penumbra.transaction.WitnessData.prototype.setNoteCommitmentProofsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.penumbra.crypto.NoteCommitmentProof=} opt_value
 * @param {number=} opt_index
 * @return {!proto.penumbra.crypto.NoteCommitmentProof}
 */
proto.penumbra.transaction.WitnessData.prototype.addNoteCommitmentProofs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.penumbra.crypto.NoteCommitmentProof, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.penumbra.transaction.WitnessData} returns this
 */
proto.penumbra.transaction.WitnessData.prototype.clearNoteCommitmentProofsList = function() {
  return this.setNoteCommitmentProofsList([]);
};


