// source: dex.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.penumbra.dex.PositionOpen');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.penumbra.dex.Position');
goog.require('proto.penumbra.dex.Reserves');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.penumbra.dex.PositionOpen = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.penumbra.dex.PositionOpen, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.penumbra.dex.PositionOpen.displayName = 'proto.penumbra.dex.PositionOpen';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.penumbra.dex.PositionOpen.prototype.toObject = function(opt_includeInstance) {
  return proto.penumbra.dex.PositionOpen.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.penumbra.dex.PositionOpen} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.dex.PositionOpen.toObject = function(includeInstance, msg) {
  var f, obj = {
    position: (f = msg.getPosition()) && proto.penumbra.dex.Position.toObject(includeInstance, f),
    initialReserves: (f = msg.getInitialReserves()) && proto.penumbra.dex.Reserves.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.penumbra.dex.PositionOpen}
 */
proto.penumbra.dex.PositionOpen.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.penumbra.dex.PositionOpen;
  return proto.penumbra.dex.PositionOpen.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.penumbra.dex.PositionOpen} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.penumbra.dex.PositionOpen}
 */
proto.penumbra.dex.PositionOpen.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.penumbra.dex.Position;
      reader.readMessage(value,proto.penumbra.dex.Position.deserializeBinaryFromReader);
      msg.setPosition(value);
      break;
    case 2:
      var value = new proto.penumbra.dex.Reserves;
      reader.readMessage(value,proto.penumbra.dex.Reserves.deserializeBinaryFromReader);
      msg.setInitialReserves(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.penumbra.dex.PositionOpen.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.penumbra.dex.PositionOpen.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.penumbra.dex.PositionOpen} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.dex.PositionOpen.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPosition();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.penumbra.dex.Position.serializeBinaryToWriter
    );
  }
  f = message.getInitialReserves();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.penumbra.dex.Reserves.serializeBinaryToWriter
    );
  }
};


/**
 * optional Position position = 1;
 * @return {?proto.penumbra.dex.Position}
 */
proto.penumbra.dex.PositionOpen.prototype.getPosition = function() {
  return /** @type{?proto.penumbra.dex.Position} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.dex.Position, 1));
};


/**
 * @param {?proto.penumbra.dex.Position|undefined} value
 * @return {!proto.penumbra.dex.PositionOpen} returns this
*/
proto.penumbra.dex.PositionOpen.prototype.setPosition = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.dex.PositionOpen} returns this
 */
proto.penumbra.dex.PositionOpen.prototype.clearPosition = function() {
  return this.setPosition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.dex.PositionOpen.prototype.hasPosition = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Reserves initial_reserves = 2;
 * @return {?proto.penumbra.dex.Reserves}
 */
proto.penumbra.dex.PositionOpen.prototype.getInitialReserves = function() {
  return /** @type{?proto.penumbra.dex.Reserves} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.dex.Reserves, 2));
};


/**
 * @param {?proto.penumbra.dex.Reserves|undefined} value
 * @return {!proto.penumbra.dex.PositionOpen} returns this
*/
proto.penumbra.dex.PositionOpen.prototype.setInitialReserves = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.dex.PositionOpen} returns this
 */
proto.penumbra.dex.PositionOpen.prototype.clearInitialReserves = function() {
  return this.setInitialReserves(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.dex.PositionOpen.prototype.hasInitialReserves = function() {
  return jspb.Message.getField(this, 2) != null;
};


