// source: transaction.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.penumbra.transaction.SpendBody');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.penumbra.crypto.ValueCommitment');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.penumbra.transaction.SpendBody = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.penumbra.transaction.SpendBody, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.penumbra.transaction.SpendBody.displayName = 'proto.penumbra.transaction.SpendBody';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.penumbra.transaction.SpendBody.prototype.toObject = function(opt_includeInstance) {
  return proto.penumbra.transaction.SpendBody.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.penumbra.transaction.SpendBody} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.transaction.SpendBody.toObject = function(includeInstance, msg) {
  var f, obj = {
    valueCommitment: (f = msg.getValueCommitment()) && proto.penumbra.crypto.ValueCommitment.toObject(includeInstance, f),
    nullifier: msg.getNullifier_asB64(),
    rk: msg.getRk_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.penumbra.transaction.SpendBody}
 */
proto.penumbra.transaction.SpendBody.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.penumbra.transaction.SpendBody;
  return proto.penumbra.transaction.SpendBody.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.penumbra.transaction.SpendBody} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.penumbra.transaction.SpendBody}
 */
proto.penumbra.transaction.SpendBody.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.penumbra.crypto.ValueCommitment;
      reader.readMessage(value,proto.penumbra.crypto.ValueCommitment.deserializeBinaryFromReader);
      msg.setValueCommitment(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setNullifier(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setRk(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.penumbra.transaction.SpendBody.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.penumbra.transaction.SpendBody.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.penumbra.transaction.SpendBody} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.transaction.SpendBody.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValueCommitment();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.penumbra.crypto.ValueCommitment.serializeBinaryToWriter
    );
  }
  f = message.getNullifier_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getRk_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
};


/**
 * optional penumbra.crypto.ValueCommitment value_commitment = 1;
 * @return {?proto.penumbra.crypto.ValueCommitment}
 */
proto.penumbra.transaction.SpendBody.prototype.getValueCommitment = function() {
  return /** @type{?proto.penumbra.crypto.ValueCommitment} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.crypto.ValueCommitment, 1));
};


/**
 * @param {?proto.penumbra.crypto.ValueCommitment|undefined} value
 * @return {!proto.penumbra.transaction.SpendBody} returns this
*/
proto.penumbra.transaction.SpendBody.prototype.setValueCommitment = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.transaction.SpendBody} returns this
 */
proto.penumbra.transaction.SpendBody.prototype.clearValueCommitment = function() {
  return this.setValueCommitment(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.transaction.SpendBody.prototype.hasValueCommitment = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bytes nullifier = 3;
 * @return {!(string|Uint8Array)}
 */
proto.penumbra.transaction.SpendBody.prototype.getNullifier = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes nullifier = 3;
 * This is a type-conversion wrapper around `getNullifier()`
 * @return {string}
 */
proto.penumbra.transaction.SpendBody.prototype.getNullifier_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getNullifier()));
};


/**
 * optional bytes nullifier = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getNullifier()`
 * @return {!Uint8Array}
 */
proto.penumbra.transaction.SpendBody.prototype.getNullifier_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getNullifier()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.penumbra.transaction.SpendBody} returns this
 */
proto.penumbra.transaction.SpendBody.prototype.setNullifier = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional bytes rk = 4;
 * @return {!(string|Uint8Array)}
 */
proto.penumbra.transaction.SpendBody.prototype.getRk = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes rk = 4;
 * This is a type-conversion wrapper around `getRk()`
 * @return {string}
 */
proto.penumbra.transaction.SpendBody.prototype.getRk_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getRk()));
};


/**
 * optional bytes rk = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getRk()`
 * @return {!Uint8Array}
 */
proto.penumbra.transaction.SpendBody.prototype.getRk_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getRk()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.penumbra.transaction.SpendBody} returns this
 */
proto.penumbra.transaction.SpendBody.prototype.setRk = function(value) {
  return jspb.Message.setProto3BytesField(this, 4, value);
};


