// source: dex.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.penumbra.dex.SwapBody');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.penumbra.crypto.NotePayload');
goog.require('proto.penumbra.dex.TradingPair');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.penumbra.dex.SwapBody = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.penumbra.dex.SwapBody, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.penumbra.dex.SwapBody.displayName = 'proto.penumbra.dex.SwapBody';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.penumbra.dex.SwapBody.prototype.toObject = function(opt_includeInstance) {
  return proto.penumbra.dex.SwapBody.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.penumbra.dex.SwapBody} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.dex.SwapBody.toObject = function(includeInstance, msg) {
  var f, obj = {
    tradingPair: (f = msg.getTradingPair()) && proto.penumbra.dex.TradingPair.toObject(includeInstance, f),
    delta1: jspb.Message.getFieldWithDefault(msg, 2, 0),
    delta2: jspb.Message.getFieldWithDefault(msg, 3, 0),
    feeCommitment: msg.getFeeCommitment_asB64(),
    swapNft: (f = msg.getSwapNft()) && proto.penumbra.crypto.NotePayload.toObject(includeInstance, f),
    swapCiphertext: msg.getSwapCiphertext_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.penumbra.dex.SwapBody}
 */
proto.penumbra.dex.SwapBody.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.penumbra.dex.SwapBody;
  return proto.penumbra.dex.SwapBody.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.penumbra.dex.SwapBody} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.penumbra.dex.SwapBody}
 */
proto.penumbra.dex.SwapBody.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.penumbra.dex.TradingPair;
      reader.readMessage(value,proto.penumbra.dex.TradingPair.deserializeBinaryFromReader);
      msg.setTradingPair(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDelta1(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDelta2(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setFeeCommitment(value);
      break;
    case 5:
      var value = new proto.penumbra.crypto.NotePayload;
      reader.readMessage(value,proto.penumbra.crypto.NotePayload.deserializeBinaryFromReader);
      msg.setSwapNft(value);
      break;
    case 6:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSwapCiphertext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.penumbra.dex.SwapBody.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.penumbra.dex.SwapBody.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.penumbra.dex.SwapBody} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.dex.SwapBody.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTradingPair();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.penumbra.dex.TradingPair.serializeBinaryToWriter
    );
  }
  f = message.getDelta1();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getDelta2();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getFeeCommitment_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = message.getSwapNft();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.penumbra.crypto.NotePayload.serializeBinaryToWriter
    );
  }
  f = message.getSwapCiphertext_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      6,
      f
    );
  }
};


/**
 * optional TradingPair trading_pair = 1;
 * @return {?proto.penumbra.dex.TradingPair}
 */
proto.penumbra.dex.SwapBody.prototype.getTradingPair = function() {
  return /** @type{?proto.penumbra.dex.TradingPair} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.dex.TradingPair, 1));
};


/**
 * @param {?proto.penumbra.dex.TradingPair|undefined} value
 * @return {!proto.penumbra.dex.SwapBody} returns this
*/
proto.penumbra.dex.SwapBody.prototype.setTradingPair = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.dex.SwapBody} returns this
 */
proto.penumbra.dex.SwapBody.prototype.clearTradingPair = function() {
  return this.setTradingPair(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.dex.SwapBody.prototype.hasTradingPair = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint64 delta_1 = 2;
 * @return {number}
 */
proto.penumbra.dex.SwapBody.prototype.getDelta1 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.penumbra.dex.SwapBody} returns this
 */
proto.penumbra.dex.SwapBody.prototype.setDelta1 = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 delta_2 = 3;
 * @return {number}
 */
proto.penumbra.dex.SwapBody.prototype.getDelta2 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.penumbra.dex.SwapBody} returns this
 */
proto.penumbra.dex.SwapBody.prototype.setDelta2 = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional bytes fee_commitment = 4;
 * @return {!(string|Uint8Array)}
 */
proto.penumbra.dex.SwapBody.prototype.getFeeCommitment = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes fee_commitment = 4;
 * This is a type-conversion wrapper around `getFeeCommitment()`
 * @return {string}
 */
proto.penumbra.dex.SwapBody.prototype.getFeeCommitment_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getFeeCommitment()));
};


/**
 * optional bytes fee_commitment = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getFeeCommitment()`
 * @return {!Uint8Array}
 */
proto.penumbra.dex.SwapBody.prototype.getFeeCommitment_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getFeeCommitment()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.penumbra.dex.SwapBody} returns this
 */
proto.penumbra.dex.SwapBody.prototype.setFeeCommitment = function(value) {
  return jspb.Message.setProto3BytesField(this, 4, value);
};


/**
 * optional penumbra.crypto.NotePayload swap_nft = 5;
 * @return {?proto.penumbra.crypto.NotePayload}
 */
proto.penumbra.dex.SwapBody.prototype.getSwapNft = function() {
  return /** @type{?proto.penumbra.crypto.NotePayload} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.crypto.NotePayload, 5));
};


/**
 * @param {?proto.penumbra.crypto.NotePayload|undefined} value
 * @return {!proto.penumbra.dex.SwapBody} returns this
*/
proto.penumbra.dex.SwapBody.prototype.setSwapNft = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.dex.SwapBody} returns this
 */
proto.penumbra.dex.SwapBody.prototype.clearSwapNft = function() {
  return this.setSwapNft(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.dex.SwapBody.prototype.hasSwapNft = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bytes swap_ciphertext = 6;
 * @return {!(string|Uint8Array)}
 */
proto.penumbra.dex.SwapBody.prototype.getSwapCiphertext = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * optional bytes swap_ciphertext = 6;
 * This is a type-conversion wrapper around `getSwapCiphertext()`
 * @return {string}
 */
proto.penumbra.dex.SwapBody.prototype.getSwapCiphertext_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSwapCiphertext()));
};


/**
 * optional bytes swap_ciphertext = 6;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSwapCiphertext()`
 * @return {!Uint8Array}
 */
proto.penumbra.dex.SwapBody.prototype.getSwapCiphertext_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSwapCiphertext()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.penumbra.dex.SwapBody} returns this
 */
proto.penumbra.dex.SwapBody.prototype.setSwapCiphertext = function(value) {
  return jspb.Message.setProto3BytesField(this, 6, value);
};


