// source: transaction.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.penumbra.transaction.SwapClaimPlan');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.penumbra.crypto.Note');
goog.require('proto.penumbra.dex.BatchSwapOutputData');
goog.require('proto.penumbra.dex.SwapPlaintext');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.penumbra.transaction.SwapClaimPlan = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.penumbra.transaction.SwapClaimPlan, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.penumbra.transaction.SwapClaimPlan.displayName = 'proto.penumbra.transaction.SwapClaimPlan';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.toObject = function(opt_includeInstance) {
  return proto.penumbra.transaction.SwapClaimPlan.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.penumbra.transaction.SwapClaimPlan} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.transaction.SwapClaimPlan.toObject = function(includeInstance, msg) {
  var f, obj = {
    swapNftNote: (f = msg.getSwapNftNote()) && proto.penumbra.crypto.Note.toObject(includeInstance, f),
    swapNftPosition: jspb.Message.getFieldWithDefault(msg, 2, 0),
    swapPlaintext: (f = msg.getSwapPlaintext()) && proto.penumbra.dex.SwapPlaintext.toObject(includeInstance, f),
    outputData: (f = msg.getOutputData()) && proto.penumbra.dex.BatchSwapOutputData.toObject(includeInstance, f),
    output1Blinding: msg.getOutput1Blinding_asB64(),
    output2Blinding: msg.getOutput2Blinding_asB64(),
    esk1: msg.getEsk1_asB64(),
    esk2: msg.getEsk2_asB64(),
    epochDuration: jspb.Message.getFieldWithDefault(msg, 20, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.penumbra.transaction.SwapClaimPlan}
 */
proto.penumbra.transaction.SwapClaimPlan.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.penumbra.transaction.SwapClaimPlan;
  return proto.penumbra.transaction.SwapClaimPlan.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.penumbra.transaction.SwapClaimPlan} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.penumbra.transaction.SwapClaimPlan}
 */
proto.penumbra.transaction.SwapClaimPlan.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.penumbra.crypto.Note;
      reader.readMessage(value,proto.penumbra.crypto.Note.deserializeBinaryFromReader);
      msg.setSwapNftNote(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setSwapNftPosition(value);
      break;
    case 3:
      var value = new proto.penumbra.dex.SwapPlaintext;
      reader.readMessage(value,proto.penumbra.dex.SwapPlaintext.deserializeBinaryFromReader);
      msg.setSwapPlaintext(value);
      break;
    case 11:
      var value = new proto.penumbra.dex.BatchSwapOutputData;
      reader.readMessage(value,proto.penumbra.dex.BatchSwapOutputData.deserializeBinaryFromReader);
      msg.setOutputData(value);
      break;
    case 15:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setOutput1Blinding(value);
      break;
    case 16:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setOutput2Blinding(value);
      break;
    case 17:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEsk1(value);
      break;
    case 18:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEsk2(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setEpochDuration(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.penumbra.transaction.SwapClaimPlan.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.penumbra.transaction.SwapClaimPlan} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.transaction.SwapClaimPlan.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSwapNftNote();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.penumbra.crypto.Note.serializeBinaryToWriter
    );
  }
  f = message.getSwapNftPosition();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getSwapPlaintext();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.penumbra.dex.SwapPlaintext.serializeBinaryToWriter
    );
  }
  f = message.getOutputData();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.penumbra.dex.BatchSwapOutputData.serializeBinaryToWriter
    );
  }
  f = message.getOutput1Blinding_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      15,
      f
    );
  }
  f = message.getOutput2Blinding_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      16,
      f
    );
  }
  f = message.getEsk1_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      17,
      f
    );
  }
  f = message.getEsk2_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      18,
      f
    );
  }
  f = message.getEpochDuration();
  if (f !== 0) {
    writer.writeUint64(
      20,
      f
    );
  }
};


/**
 * optional penumbra.crypto.Note swap_nft_note = 1;
 * @return {?proto.penumbra.crypto.Note}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.getSwapNftNote = function() {
  return /** @type{?proto.penumbra.crypto.Note} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.crypto.Note, 1));
};


/**
 * @param {?proto.penumbra.crypto.Note|undefined} value
 * @return {!proto.penumbra.transaction.SwapClaimPlan} returns this
*/
proto.penumbra.transaction.SwapClaimPlan.prototype.setSwapNftNote = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.transaction.SwapClaimPlan} returns this
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.clearSwapNftNote = function() {
  return this.setSwapNftNote(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.hasSwapNftNote = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint64 swap_nft_position = 2;
 * @return {number}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.getSwapNftPosition = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.penumbra.transaction.SwapClaimPlan} returns this
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.setSwapNftPosition = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional penumbra.dex.SwapPlaintext swap_plaintext = 3;
 * @return {?proto.penumbra.dex.SwapPlaintext}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.getSwapPlaintext = function() {
  return /** @type{?proto.penumbra.dex.SwapPlaintext} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.dex.SwapPlaintext, 3));
};


/**
 * @param {?proto.penumbra.dex.SwapPlaintext|undefined} value
 * @return {!proto.penumbra.transaction.SwapClaimPlan} returns this
*/
proto.penumbra.transaction.SwapClaimPlan.prototype.setSwapPlaintext = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.transaction.SwapClaimPlan} returns this
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.clearSwapPlaintext = function() {
  return this.setSwapPlaintext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.hasSwapPlaintext = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional penumbra.dex.BatchSwapOutputData output_data = 11;
 * @return {?proto.penumbra.dex.BatchSwapOutputData}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.getOutputData = function() {
  return /** @type{?proto.penumbra.dex.BatchSwapOutputData} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.dex.BatchSwapOutputData, 11));
};


/**
 * @param {?proto.penumbra.dex.BatchSwapOutputData|undefined} value
 * @return {!proto.penumbra.transaction.SwapClaimPlan} returns this
*/
proto.penumbra.transaction.SwapClaimPlan.prototype.setOutputData = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.transaction.SwapClaimPlan} returns this
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.clearOutputData = function() {
  return this.setOutputData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.hasOutputData = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional bytes output_1_blinding = 15;
 * @return {!(string|Uint8Array)}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.getOutput1Blinding = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * optional bytes output_1_blinding = 15;
 * This is a type-conversion wrapper around `getOutput1Blinding()`
 * @return {string}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.getOutput1Blinding_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getOutput1Blinding()));
};


/**
 * optional bytes output_1_blinding = 15;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getOutput1Blinding()`
 * @return {!Uint8Array}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.getOutput1Blinding_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getOutput1Blinding()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.penumbra.transaction.SwapClaimPlan} returns this
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.setOutput1Blinding = function(value) {
  return jspb.Message.setProto3BytesField(this, 15, value);
};


/**
 * optional bytes output_2_blinding = 16;
 * @return {!(string|Uint8Array)}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.getOutput2Blinding = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * optional bytes output_2_blinding = 16;
 * This is a type-conversion wrapper around `getOutput2Blinding()`
 * @return {string}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.getOutput2Blinding_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getOutput2Blinding()));
};


/**
 * optional bytes output_2_blinding = 16;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getOutput2Blinding()`
 * @return {!Uint8Array}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.getOutput2Blinding_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getOutput2Blinding()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.penumbra.transaction.SwapClaimPlan} returns this
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.setOutput2Blinding = function(value) {
  return jspb.Message.setProto3BytesField(this, 16, value);
};


/**
 * optional bytes esk_1 = 17;
 * @return {!(string|Uint8Array)}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.getEsk1 = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * optional bytes esk_1 = 17;
 * This is a type-conversion wrapper around `getEsk1()`
 * @return {string}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.getEsk1_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEsk1()));
};


/**
 * optional bytes esk_1 = 17;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEsk1()`
 * @return {!Uint8Array}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.getEsk1_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEsk1()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.penumbra.transaction.SwapClaimPlan} returns this
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.setEsk1 = function(value) {
  return jspb.Message.setProto3BytesField(this, 17, value);
};


/**
 * optional bytes esk_2 = 18;
 * @return {!(string|Uint8Array)}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.getEsk2 = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/**
 * optional bytes esk_2 = 18;
 * This is a type-conversion wrapper around `getEsk2()`
 * @return {string}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.getEsk2_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEsk2()));
};


/**
 * optional bytes esk_2 = 18;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEsk2()`
 * @return {!Uint8Array}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.getEsk2_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEsk2()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.penumbra.transaction.SwapClaimPlan} returns this
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.setEsk2 = function(value) {
  return jspb.Message.setProto3BytesField(this, 18, value);
};


/**
 * optional uint64 epoch_duration = 20;
 * @return {number}
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.getEpochDuration = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {number} value
 * @return {!proto.penumbra.transaction.SwapClaimPlan} returns this
 */
proto.penumbra.transaction.SwapClaimPlan.prototype.setEpochDuration = function(value) {
  return jspb.Message.setProto3IntField(this, 20, value);
};


