// source: transaction.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.penumbra.transaction.SwapPlan');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.penumbra.dex.SwapPlaintext');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.penumbra.transaction.SwapPlan = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.penumbra.transaction.SwapPlan, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.penumbra.transaction.SwapPlan.displayName = 'proto.penumbra.transaction.SwapPlan';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.penumbra.transaction.SwapPlan.prototype.toObject = function(opt_includeInstance) {
  return proto.penumbra.transaction.SwapPlan.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.penumbra.transaction.SwapPlan} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.transaction.SwapPlan.toObject = function(includeInstance, msg) {
  var f, obj = {
    swapPlaintext: (f = msg.getSwapPlaintext()) && proto.penumbra.dex.SwapPlaintext.toObject(includeInstance, f),
    feeBlinding: msg.getFeeBlinding_asB64(),
    noteBlinding: msg.getNoteBlinding_asB64(),
    esk: msg.getEsk_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.penumbra.transaction.SwapPlan}
 */
proto.penumbra.transaction.SwapPlan.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.penumbra.transaction.SwapPlan;
  return proto.penumbra.transaction.SwapPlan.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.penumbra.transaction.SwapPlan} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.penumbra.transaction.SwapPlan}
 */
proto.penumbra.transaction.SwapPlan.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.penumbra.dex.SwapPlaintext;
      reader.readMessage(value,proto.penumbra.dex.SwapPlaintext.deserializeBinaryFromReader);
      msg.setSwapPlaintext(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setFeeBlinding(value);
      break;
    case 7:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setNoteBlinding(value);
      break;
    case 8:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEsk(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.penumbra.transaction.SwapPlan.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.penumbra.transaction.SwapPlan.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.penumbra.transaction.SwapPlan} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.transaction.SwapPlan.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSwapPlaintext();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.penumbra.dex.SwapPlaintext.serializeBinaryToWriter
    );
  }
  f = message.getFeeBlinding_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
  f = message.getNoteBlinding_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      7,
      f
    );
  }
  f = message.getEsk_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      8,
      f
    );
  }
};


/**
 * optional penumbra.dex.SwapPlaintext swap_plaintext = 1;
 * @return {?proto.penumbra.dex.SwapPlaintext}
 */
proto.penumbra.transaction.SwapPlan.prototype.getSwapPlaintext = function() {
  return /** @type{?proto.penumbra.dex.SwapPlaintext} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.dex.SwapPlaintext, 1));
};


/**
 * @param {?proto.penumbra.dex.SwapPlaintext|undefined} value
 * @return {!proto.penumbra.transaction.SwapPlan} returns this
*/
proto.penumbra.transaction.SwapPlan.prototype.setSwapPlaintext = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.transaction.SwapPlan} returns this
 */
proto.penumbra.transaction.SwapPlan.prototype.clearSwapPlaintext = function() {
  return this.setSwapPlaintext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.transaction.SwapPlan.prototype.hasSwapPlaintext = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bytes fee_blinding = 5;
 * @return {!(string|Uint8Array)}
 */
proto.penumbra.transaction.SwapPlan.prototype.getFeeBlinding = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes fee_blinding = 5;
 * This is a type-conversion wrapper around `getFeeBlinding()`
 * @return {string}
 */
proto.penumbra.transaction.SwapPlan.prototype.getFeeBlinding_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getFeeBlinding()));
};


/**
 * optional bytes fee_blinding = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getFeeBlinding()`
 * @return {!Uint8Array}
 */
proto.penumbra.transaction.SwapPlan.prototype.getFeeBlinding_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getFeeBlinding()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.penumbra.transaction.SwapPlan} returns this
 */
proto.penumbra.transaction.SwapPlan.prototype.setFeeBlinding = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};


/**
 * optional bytes note_blinding = 7;
 * @return {!(string|Uint8Array)}
 */
proto.penumbra.transaction.SwapPlan.prototype.getNoteBlinding = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * optional bytes note_blinding = 7;
 * This is a type-conversion wrapper around `getNoteBlinding()`
 * @return {string}
 */
proto.penumbra.transaction.SwapPlan.prototype.getNoteBlinding_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getNoteBlinding()));
};


/**
 * optional bytes note_blinding = 7;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getNoteBlinding()`
 * @return {!Uint8Array}
 */
proto.penumbra.transaction.SwapPlan.prototype.getNoteBlinding_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getNoteBlinding()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.penumbra.transaction.SwapPlan} returns this
 */
proto.penumbra.transaction.SwapPlan.prototype.setNoteBlinding = function(value) {
  return jspb.Message.setProto3BytesField(this, 7, value);
};


/**
 * optional bytes esk = 8;
 * @return {!(string|Uint8Array)}
 */
proto.penumbra.transaction.SwapPlan.prototype.getEsk = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * optional bytes esk = 8;
 * This is a type-conversion wrapper around `getEsk()`
 * @return {string}
 */
proto.penumbra.transaction.SwapPlan.prototype.getEsk_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEsk()));
};


/**
 * optional bytes esk = 8;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEsk()`
 * @return {!Uint8Array}
 */
proto.penumbra.transaction.SwapPlan.prototype.getEsk_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEsk()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.penumbra.transaction.SwapPlan} returns this
 */
proto.penumbra.transaction.SwapPlan.prototype.setEsk = function(value) {
  return jspb.Message.setProto3BytesField(this, 8, value);
};


