// source: view.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.penumbra.view.WitnessRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.penumbra.crypto.AccountID');
goog.require('proto.penumbra.crypto.NoteCommitment');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.penumbra.view.WitnessRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.penumbra.view.WitnessRequest.repeatedFields_, null);
};
goog.inherits(proto.penumbra.view.WitnessRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.penumbra.view.WitnessRequest.displayName = 'proto.penumbra.view.WitnessRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.penumbra.view.WitnessRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.penumbra.view.WitnessRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.penumbra.view.WitnessRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.penumbra.view.WitnessRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.view.WitnessRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    accountId: (f = msg.getAccountId()) && proto.penumbra.crypto.AccountID.toObject(includeInstance, f),
    noteCommitmentsList: jspb.Message.toObjectList(msg.getNoteCommitmentsList(),
    proto.penumbra.crypto.NoteCommitment.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.penumbra.view.WitnessRequest}
 */
proto.penumbra.view.WitnessRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.penumbra.view.WitnessRequest;
  return proto.penumbra.view.WitnessRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.penumbra.view.WitnessRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.penumbra.view.WitnessRequest}
 */
proto.penumbra.view.WitnessRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.penumbra.crypto.AccountID;
      reader.readMessage(value,proto.penumbra.crypto.AccountID.deserializeBinaryFromReader);
      msg.setAccountId(value);
      break;
    case 2:
      var value = new proto.penumbra.crypto.NoteCommitment;
      reader.readMessage(value,proto.penumbra.crypto.NoteCommitment.deserializeBinaryFromReader);
      msg.addNoteCommitments(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.penumbra.view.WitnessRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.penumbra.view.WitnessRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.penumbra.view.WitnessRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.view.WitnessRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccountId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.penumbra.crypto.AccountID.serializeBinaryToWriter
    );
  }
  f = message.getNoteCommitmentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.penumbra.crypto.NoteCommitment.serializeBinaryToWriter
    );
  }
};


/**
 * optional penumbra.crypto.AccountID account_id = 1;
 * @return {?proto.penumbra.crypto.AccountID}
 */
proto.penumbra.view.WitnessRequest.prototype.getAccountId = function() {
  return /** @type{?proto.penumbra.crypto.AccountID} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.crypto.AccountID, 1));
};


/**
 * @param {?proto.penumbra.crypto.AccountID|undefined} value
 * @return {!proto.penumbra.view.WitnessRequest} returns this
*/
proto.penumbra.view.WitnessRequest.prototype.setAccountId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.view.WitnessRequest} returns this
 */
proto.penumbra.view.WitnessRequest.prototype.clearAccountId = function() {
  return this.setAccountId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.view.WitnessRequest.prototype.hasAccountId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated penumbra.crypto.NoteCommitment note_commitments = 2;
 * @return {!Array<!proto.penumbra.crypto.NoteCommitment>}
 */
proto.penumbra.view.WitnessRequest.prototype.getNoteCommitmentsList = function() {
  return /** @type{!Array<!proto.penumbra.crypto.NoteCommitment>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.penumbra.crypto.NoteCommitment, 2));
};


/**
 * @param {!Array<!proto.penumbra.crypto.NoteCommitment>} value
 * @return {!proto.penumbra.view.WitnessRequest} returns this
*/
proto.penumbra.view.WitnessRequest.prototype.setNoteCommitmentsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.penumbra.crypto.NoteCommitment=} opt_value
 * @param {number=} opt_index
 * @return {!proto.penumbra.crypto.NoteCommitment}
 */
proto.penumbra.view.WitnessRequest.prototype.addNoteCommitments = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.penumbra.crypto.NoteCommitment, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.penumbra.view.WitnessRequest} returns this
 */
proto.penumbra.view.WitnessRequest.prototype.clearNoteCommitmentsList = function() {
  return this.setNoteCommitmentsList([]);
};


