// source: src/proto/chain.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.penumbra.chain.AnnotatedNotePayload');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.penumbra.chain.NoteSource');
goog.require('proto.penumbra.crypto.NotePayload');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.penumbra.chain.AnnotatedNotePayload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.penumbra.chain.AnnotatedNotePayload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.penumbra.chain.AnnotatedNotePayload.displayName = 'proto.penumbra.chain.AnnotatedNotePayload';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.penumbra.chain.AnnotatedNotePayload.prototype.toObject = function(opt_includeInstance) {
  return proto.penumbra.chain.AnnotatedNotePayload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.penumbra.chain.AnnotatedNotePayload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.chain.AnnotatedNotePayload.toObject = function(includeInstance, msg) {
  var f, obj = {
    payload: (f = msg.getPayload()) && proto.penumbra.crypto.NotePayload.toObject(includeInstance, f),
    source: (f = msg.getSource()) && proto.penumbra.chain.NoteSource.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.penumbra.chain.AnnotatedNotePayload}
 */
proto.penumbra.chain.AnnotatedNotePayload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.penumbra.chain.AnnotatedNotePayload;
  return proto.penumbra.chain.AnnotatedNotePayload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.penumbra.chain.AnnotatedNotePayload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.penumbra.chain.AnnotatedNotePayload}
 */
proto.penumbra.chain.AnnotatedNotePayload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.penumbra.crypto.NotePayload;
      reader.readMessage(value,proto.penumbra.crypto.NotePayload.deserializeBinaryFromReader);
      msg.setPayload(value);
      break;
    case 2:
      var value = new proto.penumbra.chain.NoteSource;
      reader.readMessage(value,proto.penumbra.chain.NoteSource.deserializeBinaryFromReader);
      msg.setSource(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.penumbra.chain.AnnotatedNotePayload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.penumbra.chain.AnnotatedNotePayload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.penumbra.chain.AnnotatedNotePayload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.chain.AnnotatedNotePayload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPayload();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.penumbra.crypto.NotePayload.serializeBinaryToWriter
    );
  }
  f = message.getSource();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.penumbra.chain.NoteSource.serializeBinaryToWriter
    );
  }
};


/**
 * optional penumbra.crypto.NotePayload payload = 1;
 * @return {?proto.penumbra.crypto.NotePayload}
 */
proto.penumbra.chain.AnnotatedNotePayload.prototype.getPayload = function() {
  return /** @type{?proto.penumbra.crypto.NotePayload} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.crypto.NotePayload, 1));
};


/**
 * @param {?proto.penumbra.crypto.NotePayload|undefined} value
 * @return {!proto.penumbra.chain.AnnotatedNotePayload} returns this
*/
proto.penumbra.chain.AnnotatedNotePayload.prototype.setPayload = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.chain.AnnotatedNotePayload} returns this
 */
proto.penumbra.chain.AnnotatedNotePayload.prototype.clearPayload = function() {
  return this.setPayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.chain.AnnotatedNotePayload.prototype.hasPayload = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional NoteSource source = 2;
 * @return {?proto.penumbra.chain.NoteSource}
 */
proto.penumbra.chain.AnnotatedNotePayload.prototype.getSource = function() {
  return /** @type{?proto.penumbra.chain.NoteSource} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.chain.NoteSource, 2));
};


/**
 * @param {?proto.penumbra.chain.NoteSource|undefined} value
 * @return {!proto.penumbra.chain.AnnotatedNotePayload} returns this
*/
proto.penumbra.chain.AnnotatedNotePayload.prototype.setSource = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.chain.AnnotatedNotePayload} returns this
 */
proto.penumbra.chain.AnnotatedNotePayload.prototype.clearSource = function() {
  return this.setSource(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.chain.AnnotatedNotePayload.prototype.hasSource = function() {
  return jspb.Message.getField(this, 2) != null;
};


