// source: src/proto/crypto.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.penumbra.crypto.NotePayload');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.penumbra.crypto.NoteCommitment');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.penumbra.crypto.NotePayload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.penumbra.crypto.NotePayload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.penumbra.crypto.NotePayload.displayName = 'proto.penumbra.crypto.NotePayload';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.penumbra.crypto.NotePayload.prototype.toObject = function(opt_includeInstance) {
  return proto.penumbra.crypto.NotePayload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.penumbra.crypto.NotePayload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.crypto.NotePayload.toObject = function(includeInstance, msg) {
  var f, obj = {
    noteCommitment: (f = msg.getNoteCommitment()) && proto.penumbra.crypto.NoteCommitment.toObject(includeInstance, f),
    ephemeralKey: msg.getEphemeralKey_asB64(),
    encryptedNote: msg.getEncryptedNote_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.penumbra.crypto.NotePayload}
 */
proto.penumbra.crypto.NotePayload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.penumbra.crypto.NotePayload;
  return proto.penumbra.crypto.NotePayload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.penumbra.crypto.NotePayload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.penumbra.crypto.NotePayload}
 */
proto.penumbra.crypto.NotePayload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.penumbra.crypto.NoteCommitment;
      reader.readMessage(value,proto.penumbra.crypto.NoteCommitment.deserializeBinaryFromReader);
      msg.setNoteCommitment(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEphemeralKey(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEncryptedNote(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.penumbra.crypto.NotePayload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.penumbra.crypto.NotePayload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.penumbra.crypto.NotePayload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.crypto.NotePayload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNoteCommitment();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.penumbra.crypto.NoteCommitment.serializeBinaryToWriter
    );
  }
  f = message.getEphemeralKey_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getEncryptedNote_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
};


/**
 * optional NoteCommitment note_commitment = 1;
 * @return {?proto.penumbra.crypto.NoteCommitment}
 */
proto.penumbra.crypto.NotePayload.prototype.getNoteCommitment = function() {
  return /** @type{?proto.penumbra.crypto.NoteCommitment} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.crypto.NoteCommitment, 1));
};


/**
 * @param {?proto.penumbra.crypto.NoteCommitment|undefined} value
 * @return {!proto.penumbra.crypto.NotePayload} returns this
*/
proto.penumbra.crypto.NotePayload.prototype.setNoteCommitment = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.crypto.NotePayload} returns this
 */
proto.penumbra.crypto.NotePayload.prototype.clearNoteCommitment = function() {
  return this.setNoteCommitment(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.crypto.NotePayload.prototype.hasNoteCommitment = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bytes ephemeral_key = 2;
 * @return {!(string|Uint8Array)}
 */
proto.penumbra.crypto.NotePayload.prototype.getEphemeralKey = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes ephemeral_key = 2;
 * This is a type-conversion wrapper around `getEphemeralKey()`
 * @return {string}
 */
proto.penumbra.crypto.NotePayload.prototype.getEphemeralKey_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEphemeralKey()));
};


/**
 * optional bytes ephemeral_key = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEphemeralKey()`
 * @return {!Uint8Array}
 */
proto.penumbra.crypto.NotePayload.prototype.getEphemeralKey_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEphemeralKey()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.penumbra.crypto.NotePayload} returns this
 */
proto.penumbra.crypto.NotePayload.prototype.setEphemeralKey = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes encrypted_note = 3;
 * @return {!(string|Uint8Array)}
 */
proto.penumbra.crypto.NotePayload.prototype.getEncryptedNote = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes encrypted_note = 3;
 * This is a type-conversion wrapper around `getEncryptedNote()`
 * @return {string}
 */
proto.penumbra.crypto.NotePayload.prototype.getEncryptedNote_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEncryptedNote()));
};


/**
 * optional bytes encrypted_note = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEncryptedNote()`
 * @return {!Uint8Array}
 */
proto.penumbra.crypto.NotePayload.prototype.getEncryptedNote_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEncryptedNote()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.penumbra.crypto.NotePayload} returns this
 */
proto.penumbra.crypto.NotePayload.prototype.setEncryptedNote = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


