// source: src/proto/stake.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.penumbra.stake.ValidatorStatus');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.penumbra.crypto.IdentityKey');
goog.require('proto.penumbra.stake.BondingState');
goog.require('proto.penumbra.stake.ValidatorState');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.penumbra.stake.ValidatorStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.penumbra.stake.ValidatorStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.penumbra.stake.ValidatorStatus.displayName = 'proto.penumbra.stake.ValidatorStatus';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.penumbra.stake.ValidatorStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.penumbra.stake.ValidatorStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.penumbra.stake.ValidatorStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.stake.ValidatorStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    identityKey: (f = msg.getIdentityKey()) && proto.penumbra.crypto.IdentityKey.toObject(includeInstance, f),
    state: (f = msg.getState()) && proto.penumbra.stake.ValidatorState.toObject(includeInstance, f),
    votingPower: jspb.Message.getFieldWithDefault(msg, 3, 0),
    bondingState: (f = msg.getBondingState()) && proto.penumbra.stake.BondingState.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.penumbra.stake.ValidatorStatus}
 */
proto.penumbra.stake.ValidatorStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.penumbra.stake.ValidatorStatus;
  return proto.penumbra.stake.ValidatorStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.penumbra.stake.ValidatorStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.penumbra.stake.ValidatorStatus}
 */
proto.penumbra.stake.ValidatorStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.penumbra.crypto.IdentityKey;
      reader.readMessage(value,proto.penumbra.crypto.IdentityKey.deserializeBinaryFromReader);
      msg.setIdentityKey(value);
      break;
    case 2:
      var value = new proto.penumbra.stake.ValidatorState;
      reader.readMessage(value,proto.penumbra.stake.ValidatorState.deserializeBinaryFromReader);
      msg.setState(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setVotingPower(value);
      break;
    case 4:
      var value = new proto.penumbra.stake.BondingState;
      reader.readMessage(value,proto.penumbra.stake.BondingState.deserializeBinaryFromReader);
      msg.setBondingState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.penumbra.stake.ValidatorStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.penumbra.stake.ValidatorStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.penumbra.stake.ValidatorStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.penumbra.stake.ValidatorStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdentityKey();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.penumbra.crypto.IdentityKey.serializeBinaryToWriter
    );
  }
  f = message.getState();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.penumbra.stake.ValidatorState.serializeBinaryToWriter
    );
  }
  f = message.getVotingPower();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getBondingState();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.penumbra.stake.BondingState.serializeBinaryToWriter
    );
  }
};


/**
 * optional penumbra.crypto.IdentityKey identity_key = 1;
 * @return {?proto.penumbra.crypto.IdentityKey}
 */
proto.penumbra.stake.ValidatorStatus.prototype.getIdentityKey = function() {
  return /** @type{?proto.penumbra.crypto.IdentityKey} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.crypto.IdentityKey, 1));
};


/**
 * @param {?proto.penumbra.crypto.IdentityKey|undefined} value
 * @return {!proto.penumbra.stake.ValidatorStatus} returns this
*/
proto.penumbra.stake.ValidatorStatus.prototype.setIdentityKey = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.stake.ValidatorStatus} returns this
 */
proto.penumbra.stake.ValidatorStatus.prototype.clearIdentityKey = function() {
  return this.setIdentityKey(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.stake.ValidatorStatus.prototype.hasIdentityKey = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ValidatorState state = 2;
 * @return {?proto.penumbra.stake.ValidatorState}
 */
proto.penumbra.stake.ValidatorStatus.prototype.getState = function() {
  return /** @type{?proto.penumbra.stake.ValidatorState} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.stake.ValidatorState, 2));
};


/**
 * @param {?proto.penumbra.stake.ValidatorState|undefined} value
 * @return {!proto.penumbra.stake.ValidatorStatus} returns this
*/
proto.penumbra.stake.ValidatorStatus.prototype.setState = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.stake.ValidatorStatus} returns this
 */
proto.penumbra.stake.ValidatorStatus.prototype.clearState = function() {
  return this.setState(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.stake.ValidatorStatus.prototype.hasState = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional uint64 voting_power = 3;
 * @return {number}
 */
proto.penumbra.stake.ValidatorStatus.prototype.getVotingPower = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.penumbra.stake.ValidatorStatus} returns this
 */
proto.penumbra.stake.ValidatorStatus.prototype.setVotingPower = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional BondingState bonding_state = 4;
 * @return {?proto.penumbra.stake.BondingState}
 */
proto.penumbra.stake.ValidatorStatus.prototype.getBondingState = function() {
  return /** @type{?proto.penumbra.stake.BondingState} */ (
    jspb.Message.getWrapperField(this, proto.penumbra.stake.BondingState, 4));
};


/**
 * @param {?proto.penumbra.stake.BondingState|undefined} value
 * @return {!proto.penumbra.stake.ValidatorStatus} returns this
*/
proto.penumbra.stake.ValidatorStatus.prototype.setBondingState = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.penumbra.stake.ValidatorStatus} returns this
 */
proto.penumbra.stake.ValidatorStatus.prototype.clearBondingState = function() {
  return this.setBondingState(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.penumbra.stake.ValidatorStatus.prototype.hasBondingState = function() {
  return jspb.Message.getField(this, 4) != null;
};


